import { z } from 'zod';

// Generated by https://quicktype.io

export interface CreateCharacter {
  characterData: CharacterData;
  avatarData: AvatarData;
}

export interface AvatarData {
  faceId: string;
  eyeId: string;
  hairId: string;
  mouthId: string;
  noseId: string;
}

export interface CharacterData {
  name: string;
  description: string;
  characteristics?: string;
  nacionality: string;
  age: string;
  genderId: string;
  languageId: string;
}

export interface CreateCharacterOutput {
  avatar: Avatar;
  character: Character;
}

export interface Avatar {
  characterId: string;
  eyeId: string;
  faceId: string;
  hairId: string;
  id: string;
  mouthId: string;
  noseId: string;
}

export interface Character {
  age: string;
  characteristics: string;
  description: string;
  genderId: string;
  id: string;
  languageId: string;
  nacionality: string;
  name: string;
  roomId: any[];
  status: string;
  userId: string;
}


const Avatar = z.object({
  characterId: z.string(),
  eyeId: z.string(),
  faceId: z.string(),
  hairId: z.string(),
  id: z.string(),
  mouthId: z.string(),
  noseId: z.string(),
})

const Character = z.object({
  age: z.string(),
  characteristics: z.string(),
  description: z.string(),
  genderId: z.string(),
  id: z.string(),
  languageId: z.string(),
  nacionality: z.string(),
  name: z.string(),
  roomId: z.array(z.any()),
  status: z.string(),
  userId: z.string(),
})

export const CreateCharacterOutput = z.object({
  avatar: Avatar,
  character: Character,
})

