
export type UserLogged = {
  picture: string,
  birthdate: string,
  emailVerify: boolean,
  suscription: boolean,
  coins: number,
  gems: number,
  notifications: boolean,
  status: string
}

export type UserState = UserLogged | null

export interface RoomInfo extends characterInfo {
  roomId: string,
}

export type UserAction = {
  type: string,
  payload: UserLogged
}

export type SignUpBody = {
  nickname: string,
  email: string,
  birthdate: string,
  firebaseUid: string
}

export type characterInfo = {
  name: string,
  description: string,
  nationality: string,
  gender: string,
  age: string,
  language: string,
}

// Generated by https://quicktype.io

export interface UserInfo {
  apiKey: string;
  appName: string;
  createdAt: string;
  displayName: string;
  email: string;
  emailVerified: boolean;
  isAnonymous: boolean;
  lastLoginAt: string;
  photoURL: string;
  providerData: ProviderDatum[];
  stsTokenManager: StsTokenManager;
  uid: string;
}

export interface ProviderDatum {
  displayName: string;
  email: string;
  phoneNumber: null;
  photoURL: string;
  providerId: string;
  uid: string;
}

export interface StsTokenManager {
  accessToken: string;
  expirationTime: number;
  refreshToken: string;
}

