import { z } from 'zod';

// Generated by https://quicktype.io

export interface GameIDS {
  gender: Gender[];
  language: Language[];
}

export interface Gender {
  gender: string;
  id: string;
}

export interface Language {
  id: string;
  language: string;
}


const Gender = z.object({
  id: z.string(),
  gender: z.string(),
})

const Language = z.object({
  id: z.string(),
  language: z.string(),
})

export const GameIDS = z.object({
  gender: z.array(Gender),
  language: z.array(Language),
})

