import { z } from 'zod';

// Generated by https://quicktype.io

export interface RoomOutput {
  characterInRoom: CharacterInRoom;
  chat: Chat;
  room: Room;
}

export interface CharacterInRoom {
  characterId: string;
  id: string;
  roomId: string;
  name: string,
  hairUrl: string,
  faceUrl: string,
  noseUrl: string,
  mouthUrl: string,
  eyeUrl: string,
}

export interface Chat {
  id: string;
  roomId: string;
  userAId: string;
  userBId: string | null;
  userCId: string | null;
  userDId: string | null;
}

export interface Room {
  createdAt: string;
  id: string;
  languageId: string;
  litGenreId: string;
  locationId: string;
  status: boolean;
  turns: number;
}


export interface CreateRoom {
  characterId: string,
  turns: number,
  languageId: string,
  litGenreId: string,
  locationId: string,
}

export interface RoomItem {
  _count: Count;
  chat: Chat;
  createdAt: string;
  id: string;
  language: Language;
  languageId: string;
  litGenre: LitGenre;
  litGenreId: string;
  location: Location;
  locationId: string;
  status: boolean;
  turns: number;
}

export interface Count {
  charactersInRoom: number;
}

export interface Language {
  id: string;
  language: string;
}

export interface LitGenre {
  genre: string;
  id: string;
}

export interface Location {
  id: string;
  location: string;
  picture: string;
}

export interface RoomByIDOutput {
  charactersInRoom: CharactersInRoom[];
  chat: Chat;
  createdAt: string;
  id: string;
  language: Language;
  languageId: string;
  litGenre: LitGenre;
  litGenreId: string;
  location: Location;
  locationId: string;
  status: boolean;
  turns: number;
}

export interface CharactersInRoom {
  characterId: string;
  id: string;
  roomId: string;
  name: string,
  hairUrl: string,
  faceUrl: string,
  noseUrl: string,
  mouthUrl: string,
  eyeUrl: string,
}


export const CreateRoom = z.object({
  characterId: z.string(),
  turns: z.number(),
  languageId: z.string(),
  litGenreId: z.string(),
  locationId: z.string(),
})

export const Chat = z.object({
  id: z.string(),
  roomId: z.string(),
  userAId: z.string(),
  userBId: z.string().nullable(),
  userCId: z.string().nullable(),
  userDId: z.string().nullable(),
})

export const CharacterInRoom = z.object({
  characterId: z.string(),
  id: z.string(),
  roomId: z.string(),
  name: z.string(),
  hairUrl: z.string(),
  faceUrl: z.string(),
  noseUrl: z.string(),
  mouthUrl: z.string(),
  eyeUrl: z.string(),
})

export const CharactersInRoom = z.object({
  characterId: z.string(),
  id: z.string(),
  roomId: z.string(),
  name: z.string(),
  hairUrl: z.string(),
  faceUrl: z.string(),
  noseUrl: z.string(),
  mouthUrl: z.string(),
  eyeUrl: z.string(),
})

export const Room = z.object({
  createdAt: z.string(),
  id: z.string(),
  languageId: z.string(),
  litGenreId: z.string(),
  locationId: z.string(),
  status: z.boolean(),
  turns: z.number()
})

export const RoomOutput = z.object({
  characterInRoom: CharacterInRoom,
  chat: Chat,
  room: Room,
})


export const Count = z.object({
  charactersInRoom: z.number(),
})

export const Language = z.object({
  id: z.string(),
  language: z.string(),
})

export const LitGenre = z.object({
  genre: z.string(),
  id: z.string(),
})

export const Location = z.object({
  id: z.string(),
  location: z.string(),
  picture: z.string(),
})

export const RoomItem = z.object({
  _count: Count,
  chat: Chat,
  createdAt: z.string(),
  id: z.string(),
  language: Language,
  languageId: z.string(),
  litGenre: LitGenre,
  litGenreId: z.string(),
  location: Location,
  locationId: z.string(),
  status: z.boolean(),
  turns: z.number()
})

export const RoomsOutput = z.array(RoomItem)

export const RoomByIdOutput = z.object({
  charactersInRoom: z.array(CharactersInRoom),
  chat: Chat,
  createdAt: z.string(),
  id: z.string(),
  language: Language,
  languageId: z.string(),
  litGenre: LitGenre,
  litGenreId: z.string(),
  location: Location,
  locationId: z.string(),
  status: z.boolean(),
  turns: z.number()
})
