import { z } from 'zod';

// Generated by https://quicktype.io

export interface User {
  birthdate: string;
  characters: Character[] | [];
  coins: number;
  createdAt: string;
  email: string;
  emailVerify: boolean;
  firebaseUid: string;
  gems: number;
  id: string;
  nickname: string;
  notifications: boolean;
  picture: string;
  status: string;
  suscription: boolean;
  updatedAt: null;
}

export interface Character {
  age: string;
  characteristics: string;
  description: string;
  genderId: string;
  id: string;
  languageId: string;
  nacionality: string;
  name: string;
  roomId: string[];
  status: string;
  userId: string;
  avatar: Avatar,
}

export interface Avatar {
  characterId: string;
  id: string;
  eyeId: string;
  hairId: string;
  mouthId: string;
  faceId: string;
  noseId: string;
}

export const Avatar = z.object({
  id: z.string(),
  characterId: z.string(),
  eyeId: z.string(),
  hairId: z.string(),
  mouthId: z.string(),
  faceId: z.string(),
  noseId: z.string(),
})

export const Character = z.object({
  age: z.string(),
  characteristics: z.string(),
  description: z.string(),
  genderId: z.string(),
  id: z.string(),
  languageId: z.string(),
  nacionality: z.string(),
  name: z.string(),
  roomId: z.array(z.string()),
  status: z.string(),
  userId: z.string(),
  avatar: Avatar,
})

export const User = z.object({
  birthdate: z.string(),
  characters: z.array(Character),
  coins: z.number(),
  createdAt: z.string(),
  email: z.string(),
  emailVerify: z.boolean(),
  firebaseUid: z.string(),
  gems: z.number(),
  id: z.string(),
  nickname: z.string(),
  notifications: z.boolean(),
  picture: z.string(),
  status: z.string(),
  suscription: z.boolean(),
  updatedAt: z.null(),
})



