import { z } from 'zod';

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CreateMessageOutput {
  chatId: string | null;
  content: string;
  conversationId: string | null;
  createdAt: string;
  id: string;
  userId: string;
}

export interface ChatByIdOutput {
  id: string;
  messages: Message[];
  roomId: string;
  userAId: string;
  userBId: string | null;
  userCId: string | null;
  userDId: string | null;
}

export interface Message {
  chatId: string;
  content: string;
  conversationId: string | null;
  createdAt: string;
  id: string;
  userId: string;
}

export const Message = z.object({
  chatId: z.string(),
  content: z.string(),
  conversationId: z.string().nullable(),
  createdAt: z.string(),
  id: z.string(),
  userId: z.string(),
})

export const ChatByIdOutput = z.object({
  id: z.string(),
  messages: z.array(Message),
  roomId: z.string(),
  userAId: z.string(),
  userBId: z.string().nullable(),
  userCId: z.string().nullable(),
  userDId: z.string().nullable(),
})

export const CreateMessageOutput = z.object({
  chatId: z.string().nullable(),
  content: z.string(),
  conversationId: z.string().nullable(),
  createdAt: z.string(),
  id: z.string(),
  userId: z.string(),
})

